### ISSUE TITLE
New Tags for better issue structuring

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledger/fabric-private-chaincode#251]
As discussed today we should carefully use the tag system in github to organize our issues better.

We could have the following feature tags:

- Test
- Documentation (I guess we already have that one)
- 

We could have the following component tags:

- ERCC
- TLCC
- FPC Shim
- FPC Validation
- FPC Examples
- Client SDK

WDYT? Please discuss

**Comment by g2flyer** [comment]
For features i was more initially thinking of component cross-cutting stuff like key-management or alike, but right now i'm actually also not getting more for that list and that item alone doesn't deserve a separate category.

We should though have a tag capturing priority, in particular i think we need a label for
- MVP (minimal viable product / an issue we must resolve before we can get into fabric)

Regarding components, there is probably also one for "infrastructure" or alike which captures the network scripts and alike?  There is also "Demo" (but that tag already exists)

Lastly, i think it would be good if we can distinguish the different catogories:  If we can color-code them, that's probably the easiest.  Otherwise we could prefix them with something like 'c:' and 'f:' ?

**Comment by g2flyer** [comment]
After last discussion, we decided that priority as far as MVP goes is done via a milestone. I've created now a corresponding [MVP milestone](https://github.com/hyperledger-labs/fabric-private-chaincode/milestone/38), a `feature` label, created issues from the MVP list in https://docs.google.com/document/d/1ztdJykj4I-e9G-YGGnn2ExDVCQQHmbuhgdaA5HWkd9M and assigned the MVP version of it to the milestone ....

**Comment by g2flyer** [comment]
@mbrandenburger will you create the labels? See also the PR #302 for potential templates we could use in this context. Depending on how you create labels, you might want update the templates?
